version: "3.9"

services:
  db:
    image: mongo
    container_name: server_db
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - server_db_data:/data/db
    ports:
      - 27017:27017

  web:
    container_name: server_app
    build: .
    ports:
      - 7000:7000
    depends_on:
      - db
    environment:
      MONGO_USER: mongodb
      MONGO_PASSWORD: mongodb
      MONGO_HOST: server_db
      MONGO_PORT: 27017
      MONGO_DB: mongodb
      MONGO_AUTH_SOURCE: admin
      
volumes: 
    server_db_data:
    

